### ISSUE TITLE
Feature Request: Support different settings/device emulations

### ISSUE THREAD

**Issue by gidztech** [boyney123/garie-lighthouse#7]
Currently, Garie only does Lighthouse reports on the default mobile preset. However, I would like to run my audits in Desktop mode. Lighthouse supports a `settings` object to provide overrides. It would be good if Garie exposed an API to pass these in. 

See: https://github.com/boyney123/garie-lighthouse/blob/master/src/light-house/index.js#L57

You could also allow for alternative presets, e.g. there's one for Desktop here:
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/lr-desktop-config.js

I'm not totally sure exactly how you reference these but it might be like `lighthouse:lr-desktop`.

**Comment by gidztech** [comment]
Created a PR for this: https://github.com/boyney123/garie-lighthouse/pull/8

**Comment by boyney123** [comment]
Thanks @gidztech ! The change has been merged and released in 2.0
